# Generated by Django 5.2.14 on 2026-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_organization_and_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('internal_superadmin', 'Internal Superadmin'), ('internal_admin', 'Internal Admin'), ('external_superadmin', 'External Superadmin'), ('external_admin', 'External Admin')], default='external_admin', max_length=32),
        ),
    ]
