# Generated by Django 5.2.14 on 2026-08-05 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0015_project_plans_own_doi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_global_id', models.CharField(blank=True, help_text='Survey123 GlobalID when imported from legacy export.', max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('applicant_name', models.CharField(max_length=255)),
                ('title_position', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('co_pi', models.TextField(blank=True, help_text='Co-PI names and affiliations.')),
                ('project_title', models.CharField(max_length=500)),
                ('project_type', models.CharField(choices=[('Plant_material_collections', 'Plant material collections'), ('onsite_research', 'On-site research')], max_length=64)),
                ('description', models.TextField(help_text='Project description / abstract.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('anticipated_start_date', models.DateField(blank=True, null=True)),
                ('anticipated_end_date', models.DateField(blank=True, null=True)),
                ('desired_species', models.TextField(blank=True)),
                ('collection_type', models.CharField(blank=True, choices=[('on-site_collection', 'On-site collection'), ('off-site_collection', 'Off-site collection'), ('other', 'Other / not applicable')], max_length=64)),
                ('research_location', models.TextField(blank=True)),
                ('plant_tracker_notes', models.TextField(blank=True)),
                ('abiotic_variables', models.TextField(blank=True)),
                ('biotic_variables', models.TextField(blank=True)),
                ('funding_sources', models.TextField(blank=True)),
                ('wildlife_permits', models.TextField(blank=True)),
                ('nybg_infrastructure', models.TextField(blank=True)),
                ('site_visits', models.TextField(blank=True)),
                ('visitor_impacts', models.TextField(blank=True)),
                ('research_sensitivity', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('publications', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('attestation_name', models.CharField(help_text='PI name confirming they completed this application.', max_length=255)),
                ('attestation_date', models.DateField()),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional portal project linked after approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_applications', to='datasets.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_research_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research application',
                'verbose_name_plural': 'Research applications',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
    ]
