# Generated by Django 5.2.14 on 2026-08-05 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_research_application'),
        ('datasets', '0015_project_plans_own_doi'),
        ('organizations', '0002_organization_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchapplication',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Portal organization for the researcher. Required before Approve & invite.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_applications', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='researchapplication',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Portal project created when the applicant claims their invite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_applications', to='datasets.project'),
        ),
    ]
