# Generated by Django 5.2.14 on 2026-08-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_invite_org_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySurvey123Application',
            fields=[
            ],
            options={
                'verbose_name': 'Survey123 legacy application',
                'verbose_name_plural': 'Survey123 legacy backlog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.researchapplication',),
        ),
    ]
